object Versions {
    const val kotlin = "1.7.20"
    const val gradle = "7.3.0"
    const val koin = "3.2.2"
    const val kotlinSerialization = "1.6.10"
    const val kotlinxSerialization = "1.2.2"
    const val kotlinxCoroutines = "1.6.4"
    const val kotlinxTestResources = "0.2.2"
    const val ktor = "2.2.2"
    const val sqlDelight = "1.5.4"
    const val compose = "1.3.3"
    const val composeComplier = "1.3.2"
    const val compose_activity = "1.4.0"
    const val compose_constraint = "1.0.0-rc01"
    const val composeMat3 = "1.0.0-alpha13"
    const val lifecycle = "2.3.1"
    const val androidTestCore = "1.4.0"
    const val napierVersion = "2.6.1"
}